package io.justme.lavender.ui.screens.clickgui.imgui.theme;

public enum ThemeColorEnum {

    CLICKSCREEN_BACKGROUND,

    // panel
    PANEL_SETTING_TITLE,
    PANEL_SETTING_TITLE_FONT,
    PANEL_POPUP_TEXT,
    PANEL_POPUP_TOGGLE_ON,
    PANEL_POPUP_TOGGLE_OFF,
    PANEL_POPUP_HIGHLIGHT,
    PANEL_POPUPCOMBOBOX_MASK,
    PANEL_MODULEPANEL_BACKGROUND,
    PANEL_MODULE_BACKGROUND,
    PANEL_MODULE_FONT,
    PANEL_MODULE_OTHER_BUTTON_FONT,
    PANEL_MODULE_BUTTON_TOGGLE_ON,
    PANEL_MODULE_BUTTON_TOGGLE_OFF,
    PANEL_MODULE_BUTTON_FONT,
    //USERINFO
    PANEL_USERINFO_BACKGROUND,
    PANEL_USERINFO_TITLE_FONT,

    // components
    COMPONENT_CHECKBOX_FONT,
    COMPONENT_CHECKBOX_CHECKED,
    COMPONENT_CHECKBOX_UNCHECKED,
    COMPONENT_CHECKBOX_OUTLINE,
    COMPONENT_CHECKBOX_MARK,
    COMPONENT_CHECKBOX_SHADOW,

    COMPONENT_COMBOBOX_BACKGROUND,
    COMPONENT_COMBOBOX_OUTLINE,
    COMPONENT_COMBOBOX_FONT,

    COMPONENT_MODE_BACKGROUND,
    COMPONENT_MODE_OUTLINE,
    COMPONENT_MODE_FONT,
    COMPONENT_MODE_DROPDOWN_BACKGROUND,
    COMPONENT_MODE_DROPDOWN_OUTLINE,

    COMPONENT_SEGMENTEDBUTTON_BACKGROUND,
    COMPONENT_SEGMENTEDBUTTON_SELECTED,
    COMPONENT_SEGMENTEDBUTTON_OUTLINE,
    COMPONENT_SEGMENTEDBUTTON_FONT,

    COMPONENT_SLIDER_BACKGROUND,
    COMPONENT_SLIDER_FILLED,
    COMPONENT_SLIDER_OUTLINE,
    COMPONENT_SLIDER_KNOB,
    COMPONENT_SLIDER_FONT,

    COMPONENT_SWITCH_BACKGROUND,
    COMPONENT_SWITCH_ON,
    COMPONENT_SWITCH_OFF,
    COMPONENT_SWITCH_OUTLINE,
    COMPONENT_SWITCH_KNOB,
    COMPONENT_SWITCH_FONT,

    COMPONENT_SCROLLBAR_BACKGROUND,
    COMPONENT_SCROLLBAR_THUMB,

    CONFIG_UI_BUTTON_SELECT,
    CONFIG_UI_BUTTON_UNSELECT,
    CONFIG_UI_SMAIL_BUTTON,

}
